VERILOG = ../src/ulx4m_atom.v ../src/cpu.v ../src/ALU.v ../src/mc6847.v \
	  ../src/charrom.v ../src/vid_ram.v ../src/ram.v ../src/keyboard.v ../src/ps2_intf.v \
	  ../src/flashmem.v ../src/m6522.v ../src/spi.v ../src/sid/sid_6581.v ../src/sid/sid_coeffs.v \
	  ../src/sid/sid_components.v ../src/sid/sid_filters.v ../src/sid/sid_voice.v pll.v ../src/hdmi.v

TOP = atom

include ulx4m.mk

